const express = require("express");
const router = express.Router();
const noteController = require("../controllers/note.controller");

router.post("/", noteController.createNote);
router.post("/bulk", noteController.createBulkNotes);
router.get("/", noteController.getAllNotes);
router.delete("/bulk", noteController.deleteBulkNotes);
router.get("/category/:category", noteController.getNotesByCategory);
router.get("/status/:isPinned", noteController.getNotesByStatus);
router.get("/filter", noteController.filterNotes);
router.get("/filter/pinned", noteController.getPinnedNotes);
router.get("/filter/category", noteController.filterByCategory);
router.get("/filter/date-range", noteController.filterByDateRange);
router.get("/paginate", noteController.paginateNotes);
router.get("/paginate/category/:category", noteController.paginateNotesByCategory);
router.get("/sort", noteController.sortNotes);
router.get("/sort/pinned", noteController.sortPinnedNotes);
\nrouter.get("/:id", noteController.getNoteById);
router.put("/:id", noteController.replaceNote);
router.patch("/:id", noteController.updateNote);
router.delete("/:id", noteController.deleteNote);
router.get("/:id/summary", noteController.getNoteSummary);
\nmodule.exports = router;